# Generated by Django 4.0.6 on 2022-07-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
