# Generated by Django 4.0.5 on 2022-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
