# Generated by Django 4.0.6 on 2022-07-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_created']},
        ),
    ]
